---
- name: Fail if missing required variables
  fail: msg="The variable {{ item }} is must be defined"
  when: (vars[item] is undefined) or (vars[item] == "") or (vars[item] == vars[item] | bool) or not (vars[item] | default('') | length > 0)
  loop: "{{ required_variables }}"

# TODO: Validate honeypot credentials

# TODO: Get sensor_name from server

- name: Discover config from Honeydeck Server
  uri: 
    url: "{{ honeydeck_server }}/api/v1/sensors/discover/"
    headers: 
      HONEYDECK_TOKEN: "{{ honeydeck_token }}"
  register: discovery_response
  failed_when: discovery_response.status == 404 or discovery_response == 503

- name: Parse config json
  set_fact: 
    sensor_config: {{ discovery_response.msg | from_json }}

- name: Set sensor_name to configured name
  set_fact:
    sensor_name: "{{ sensor_config.name }}"
    sensor_roles: "{{ sensor_config.roles }}"