---
- name: Report Success to Server
  uri:
    url: "{{ honeydeck_server }}/api/v1/sensors/discover/"
    method: POST
    body_format: json
    body: "{{ body }}"
    return_content: no
    headers:
      Content-Type: "application/json"
      Honeydeck-Token: "{{ honeydeck_token }}"
  register: hd_sensor_validate
  vars:
    body:
      success: True
