---
- name: Get checksum of current config file
  stat:
    path: "{{ cowrie_run_dir }}/etc/cowrie.cfg"
    checksum_algorithm: md5
    get_checksum: yes
    get_attributes: no
    get_mime: no
  register: cowrie_cfg_stat

- name: Get Latest config from honeydeck server
  uri:
    url: "{{ honeydeck_sensor.honeydeck_server }}/api/v1/sensors/discovery/"
    method: GET
    return_content: yes
    headers:
      Content-Type: "application/json"
      Honeydeck-Token: "{{ honeydeck_sensor.honeydeck_token }}"
  register: honeydeck_server_config

- name: Write cowrie config from server
  copy:
    # Dirty hack until we have more than one config to look at
    content:  "{{ honeydeck_server_config.json.configs[0].config }}"
    dest: "{{ cowrie_run_dir }}/etc/cowrie.cfg"

- name: Report Success to Server
  uri:
    url: "{{ honeydeck_sensor.honeydeck_server}}/api/v1/sensors/discovery/"
    method: PUT
    body_format: json
    body: "{{ body | to_json }}"
    return_content: no
    headers:
      Content-Type: "application/json"
      Honeydeck-Token: "{{ honeydeck_sensor.honeydeck_token }}"
  vars:
    body:
      success: True
      checksum: "{{ cowrie_cfg_stat.stat.checksum | default('') }}"
