---
- name: Set fake hostname
  ini_file:
    path: "{{ cowrie_run_dir }}/etc/cowrie.cfg"
    section: honeypot
    option: hostname
    value: "{{ public_ip }}"
  notify: "Start or restart cowrie"

- name: Set sensor name
  ini_file:
    path: "{{ cowrie_run_dir }}/etc/cowrie.cfg"
    section: honeypot
    option: sensor_name
    value: "{{ sensor_name }}"
  notify: "Start or restart cowrie"

- name: Set cowrie internet facing ip
  ini_file:
    path: "{{ cowrie_run_dir }}/etc/cowrie.cfg"
    section: honeypot
    option: internet_facing_ip
    value: "{{ public_ip }}"
  notify: "Start or restart cowrie"