---
- name: Define ssh_honeypot module directory
  set_fact: 
    ssh_honeypot_dir: ../modules/ssh_honeypot

- name: Create a directory if it does not exist
  file:
    path: "{{ ssh_honeypot_dir }}"
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{ cowrie_release_url }}"
    dest: "{{ ssh_honeypot_dir }}"
    remote_src: yes

