---
- name: Create a directory if it does not exist
  file:
    path: "{{ ssh_honeypot_dir }}"
    state: directory

- name: Download and unarchive cowrie release from github
  unarchive:
    src: "{{ cowrie_release_url }}"
    dest: "{{ ssh_honeypot_dir }}"
    remote_src: yes

# Workaround for: https://github.com/ansible/ansible/issues/22967#issuecomment-500604054
- name: Get present working directory
  command: pwd
  register: pwd
  changed_when: false

- name: Create virtualenv for cowrie
  pip:
    chdir: "{{ pwd.stdout }}/{{ cowrie_run_dir }}"
    virtualenv: "cowrie-env"
    virtualenv_command: "python3 -m venv --copies"
    requirements: "requirements.txt"

- name: Allow cowrie-env python executable to bind to 22
  capabilities:
    path: "{{ pwd.stdout }}/{{ cowrie_run_dir }}/cowrie-env/bin/python"
    capability: "cap_net_bind_service=+ep"
    state: present
  become: True

- name: Allow cowrie-env python3 executable to bind to 22
  capabilities:
    path: "{{ pwd.stdout }}/{{ cowrie_run_dir }}/cowrie-env/bin/python3"
    capability: "cap_net_bind_service=+ep"
    state: present
  become: True

- name: Include pre-configurations from honeydeck server
  include_tasks:
    file: cowrie_pre_conf.yml

- name: Include pre-configurations from honeydeck server
  include_tasks:
    file: cowrie_post_conf.yml

- name: Set listen port for cowrie
  ini_file:
    path: "{{ cowrie_run_dir }}/etc/cowrie.cfg"
    section: ssh
    option: listen_endpoints
    value: "tcp6:22:interface=\\:\\:"
  notify: "Start or restart cowrie"

- name: Flush handlers to start cowrie
  meta: flush_handlers
