---
- name: OS Configurations
  include_tasks:
    file: "os.yml"
    apply:
      become: yes
  when: not (lookup('env', 'RS_IS_DOCKER') | bool)

- name: SSH Port Swap Configuration
  include_tasks:
    file: "ssh_port_swap.yml"
    apply:
      become: yes
  when: not (lookup('env', 'RS_IS_DOCKER') | bool)

- name: SSH Honeypot Configuration
  include_tasks:
    file: "cowrie.yml"
    apply:
      become: no
