---
- name: SSH Honeypot Configuration
  include_tasks:
    file: "{{ item.filename }}"
    apply:
      become: "{{ item.become | default('no') }}"
  loop:
    - filename: os.yml
      become: yes
    - filename: ssh_port_swap.yml
      become: yes
    - filename: cowrie.yml
    - filename: system_service.yml
      become: yes
