---
- name: OS configuration
  include_tasks: "{{ item.filename }}"
  apply: "{{ item.applies }}"
  loop:
    - { filename: "os.yml", applies: { become: True } }
    - { filename: "ssh_port_swap.yml", applies: { become: True } }
    - { filename: "cowrie.yml" }
