---
# Defaults:
#   become: yes

- name: Update all the things!
  yum:
    name: '*'
    state: latest
  when: ansible_os_family=='RedHat'

- name: Update all the things!
  apt:
    name: '*'
    state: latest
  when: ansible_os_family=='Debian'

# Workaround for bug: https://github.com/ansible/ansible/issues/56583
# In future, will use yum module's `lock_timeout: 60`
- name: Wait until yum is unlocked
  wait_for:
    path: "/var/run/yum.pid"
    state: absent
  when: ansible_os_family=='RedHat'

- name: Install required packages
  yum:
    name: 
      - firewalld
    state: latest
    lock_timeout: 60 # Ansible bug: https://github.com/ansible/ansible/issues/56583
  when: ansible_os_family=='RedHat'

- name: Install required packages
  apt:
    name: 
      - firewalld
      - unzip
      - python3-venv
    state: latest
  when: ansible_os_family=='Debian'

- name: Start firewalld
  systemd:
    state: started
    name: firewalld

- name: Open Alternative SSH Port
  firewalld:
    port: "{{ replacement_ssh_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when: ansible_os_family=='RedHat'

- name: Open Alternative SSH Port
  firewalld:
    port: "{{ replacement_ssh_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when: ansible_os_family=='Debian'