---
# Defaults:
#   become: yes

- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ replacement_ssh_port }}"
  notify: Restart sshd
